on: push
name: build and test app
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: subosito/flutter-action@v1
      with:
        args: pub get

    - name: run tests
      uses: subosito/flutter-action@v1
      with:
        args: test